pages:
  stage: deploy
  script:
    # There has to be at least one command in the script
    - echo "This site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      # Must be always public for GitLab
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
