project:
  type: website
  output-dir: docs

website:
  title: "seergi's blog"
  description: "Data and computer science personal blog"
  site-url: "https://seergidev.github.io"
  navbar:
    right:
      - text: "About me"
        file: about.qmd
      - icon: github
        href: https://github.com/seergidev/seergidev.github.io/
        aria-label: GitHub
      - icon: git
        href: https://gitlab.com/seergidev/seergidev.gitlab.io/
        aria-label: GitLab
      - text: "Dark mode:"
        file: about.qmd
format:
  html:
    theme:
      light: flatly
      dark: darkly
    mermaid:
      theme: default
    css: styles.css

editor: visual
